// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvaibvftuxscdidworzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12YWlidmZ0dXhzY2RpZHdvcnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMjQxNDIsImV4cCI6MjA1MTYwMDE0Mn0.iuxxAQdQYtlwAeSz5K0a9tripL29D7bGpwHfdxg0IS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);